# Azure Pipelines to build GDAL documentation
#
variables:
  system.debug: true
  configuration: release

jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: none
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'pdal-docs-ssh-key'
        displayName: 'Get deploy key'
      - script: |
          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        displayName: 'Deploy'
