# Azure Pipelines to build GDAL documentation

variables:
  #system.debug: true
  configuration: release

jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Setup Python'
        inputs:
          versionSpec: '3.7'
          addToPath: true
      - script: |
          python --version
          python -m pip install --upgrade pip
          pip install -r gdal/doc/requirements.txt
        displayName: 'Setup Python'
      - script: |
          cd gdal/doc
          make html
        displayName: 'Build documentation'
