# Azure Pipelines to build GDAL documentation

variables:
  #system.debug: true
  configuration: release

jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Setup Python'
        inputs:
          versionSpec: '3.7'
          addToPath: true
      - script: |
          python --version
          cd gdal/doc
          pip --upgrade install -r requirements.txt
      - script: |
          cd gdal/doc
          make html
