# Azure Pipelines to build GDAL documentation
#
variables:
  #system.debug: true
  configuration: release

jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: osgeo/gdal-docs
        options: --privileged
    steps:
      - script: |
          python3 --version
          sphinx-build --version
        displayName: 'Sphinx version'
      - script: |
          cd $AZURE_BUILDDIRECTORY/gdal/doc
          make html
        displayName: 'Build'
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'pdal-docs-ssh-key'
        displayName: 'Get the deploy key'
      - script: |
          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        displayName: 'Deploy the key'
      - script: |
          mv $AZURE_BUILDDIRECTORY/gdal/doc/build/html $AZURE_BUILDDIRECTORY/gdal-docs
          git init
          git config user.email "proj4bot@proj4.bot"
          git config user.name "GDAL Bot"
          git remote add origin git@github.com:OSGeo/gdal-docs.git
          echo "gdal.dev" > CNAME
          git add -A
          git commit -m "Update with https://github.com/OSGeo/gdal/commit/$BUILD_SOURCEVERSION"
          git push -f origin master
        displayName: 'Deploy the docs'
