# Azure Pipelines to build GDAL documentation
#
variables:
  system.debug: true
  configuration: release

jobs:
  - job: 'Documentation'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: none
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'pdal-docs-ssh-key'
      - script: |
          echo $$DOWNLOADSECUREFILE_SECUREFILEPATH
        displayName: 'Deploy'
